# Automatically migrated from legacy .beetsconfig.

import:
    move: yes
    resume: ask

plugins: fromfilename

directory: ~/music
ignore: ._* *~ .DS_Store *.ini *.txt
library: ~/.config/beets/beetslibrary.blb
asciify_paths: yes

paths:
    default: $albumartist/$album/$track-$title
    singleton: Rnd/$artist-$title
    comp: VA/$album/$track-$title
    albumtype:soundtrack: Soundtracks/$album/$track-$title
